# Day temperature (5700K) starting at 8:00 AM
profile {
    time = 08:00
    temperature = 5700
}

# Night temperature (2700K) starting at 9:00 PM (21:00)
profile {
    time = 21:00
    temperature = 2700
}
